// src/models/contractTemplateModel.js

const db = require('../db');

/**
 * 檢查並創建 'contract_templates' 資料表 (如果不存在)。
 */
async function createContractTemplatesTable() {
  const queryText = `
    CREATE TABLE IF NOT EXISTS contract_templates (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      content TEXT NOT NULL,
      logo_url TEXT,
      variables JSONB,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `;
  try {
    await db.query(queryText);
    await db.query('ALTER TABLE contract_templates ADD COLUMN IF NOT EXISTS logo_url TEXT;');
    console.log('Contract templates table checked/created successfully.');
  } catch (error) {
    console.error('Error creating contract templates table:', error.message);
    throw error;
  }
}

async function findAll() {
  const { rows } = await db.query('SELECT * FROM contract_templates ORDER BY created_at DESC');
  return rows;
}

/**
 * 建立新合約範本。
 * @param {object} templateData - 包含 name, content, variables, logo_url 的物件。
 * @returns {object} - 新建立的範本物件。
 */
async function create({ name, content, variables, logo_url, requires_approval }) {
  const queryText = `
    INSERT INTO contract_templates (name, content, variables, logo_url, requires_approval)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING *;
  `;
  // 如果 variables 是 JS 物件/陣列，需要轉換成 JSON 字串
  const values = [name, content, JSON.stringify(variables), logo_url || null, requires_approval !== false]; // Default true
  const { rows } = await db.query(queryText, values);
  return rows[0];
}

/**
 * 查找所有啟用的合約範本。
 * @returns {Array<object>} - 範本物件陣列。
 */
async function findAllActive() {
  const queryText = 'SELECT id, name, is_active, variables, requires_approval FROM contract_templates WHERE is_active = TRUE ORDER BY id ASC';
  const { rows } = await db.query(queryText);
  return rows;
}

/**
 * 根據 ID 查找單一合約範本。
 * @param {number} id - 範本 ID。
 * @returns {object|null} - 範本物件或 null。
 */
async function findById(id) {
  const queryText = 'SELECT * FROM contract_templates WHERE id = $1';
  const { rows } = await db.query(queryText, [id]);
  return rows[0] || null;
}

/**
 * 更新合約範本。
 * @param {number} id - 範本 ID。
 * @param {object} fields - 包含 name, content, variables, is_active, logo_url 的物件。
 * @returns {object|null} - 更新後的範本物件或 null。
 */
async function update(id, { name, content, variables, is_active, logo_url, requires_approval }) {
  const queryText = `
    UPDATE contract_templates
    SET name = $1, content = $2, variables = $3, is_active = $4, logo_url = $5, requires_approval = $6, updated_at = CURRENT_TIMESTAMP
    WHERE id = $7
    RETURNING *;
  `;
  const values = [name, content, JSON.stringify(variables), is_active, logo_url || null, requires_approval !== false, id];
  const { rows } = await db.query(queryText, values);
  return rows[0] || null;
}

async function setActive(id, isActive) {
  const queryText = `
    UPDATE contract_templates
    SET is_active = $1, updated_at = CURRENT_TIMESTAMP
    WHERE id = $2
    RETURNING *;
  `;
  const { rows } = await db.query(queryText, [isActive, id]);
  return rows[0] || null;
}


module.exports = {
  createContractTemplatesTable,
  findAll,
  create,
  findAllActive,
  findById,
  update,
  setActive,
};
