name: Deploy Firebase (Functions + Firestore + Hosting) on merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 依你的 Functions runtime 調整

      - name: Install Firebase Tools
        run: npm i -g firebase-tools@latest

      - name: Auth with Service Account
        run: |
          cat > $HOME/gcloud.json <<'JSON'
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRACTTRAVELJOLLIFY }}
          JSON
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV
        
      # 若你的 functions 需要先安裝依賴，取消註解以下兩步
      - name: Install functions deps
        run: |
             if [ -f functions/package.json ]; then
             cd functions && npm ci
             fi

      - name: Deploy Functions + Firestore (rules/indexes)
        run: |
          firebase use contracttraveljollify
          firebase deploy --only "functions,firestore:rules,firestore:indexes"

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRACTTRAVELJOLLIFY }}
          projectId: contracttraveljollify
          channelId: preview
          firebaseToolsVersion: latest
          disableComment: false
          force: true
