name: Deploy Firebase (Functions + Firestore + Hosting) on merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRACTTRAVELJOLLIFY }}

      - name: Install Firebase Tools
        run: npm i -g firebase-tools@latest

      - name: Install functions deps
        working-directory: functions
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Deploy Functions + Firestore (rules/indexes)
        run: |
          firebase use contracttraveljollify
          firebase deploy --only "functions,firestore:rules,firestore:indexes"

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRACTTRAVELJOLLIFY }}
          projectId: contracttraveljollify
          channelId: live           # ← 如果要正式站
          firebaseToolsVersion: latest
          disableComment: false
          force: true
